feat: try things in error message

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -16,7 +16,7 @@ jobs:
         - name: checkout
           uses: actions/checkout@v3
 
-        - name: coding_style_check
+        - name: run_coding_style
           run: check.sh $(pwd) $(pwd)
           continue-on-error: true
 
@@ -31,7 +31,9 @@ jobs:
 
         - name: display_error
           if: ${{ failure() }}
-          run: echo "::error file=coding-style-reports.log::mehh"
+          run: |
+            echo "::error file=coding-style-reports.log,title="major/minor coding style error"::error code"
+            exit 1
 
     check_program_compilation:
         needs: [check_coding_style]
